### PR TITLE
SWC snacks & supplies and Starbucks gift cards

### PR DESCRIPTION
**Pull request by mbonsma**
Note: 2 Starbucks cards remain unused: one I didn't get an address for (Shyam), and the other was extra. We can use those this term. 

Also note: missing one receipt for SWC snacks - I think it's in the UofT Coders box, will check on Thursday.

### CODE REVIEW

**Comment by QuLogic** [comment]
Can you rotate the second image?

**Comment by mbonsma** [comment]
I guess I could, yeah...

**Comment by mbonsma** [comment]
It didn't work - I tried opening in Shotwell and rotating and saving, then I tried cropping it, but it's still horizontal.
Sounds like this might be a [known problem](https://stackoverflow.com/questions/19434073/how-can-i-avoid-that-github-rotates-my-jpg-in-my-readme-md)?

**Comment by lwjohnst86** [comment]
I'd recommend installing Imagemagick:
```
sudo apt-get install imagemagick
```
... and use this command in the terminal:

```
# Rotate image minus 90 degrees
convert -rotate "-90" in.jpg out.jpg
```

**Comment by mbonsma** [comment]
Can we do the reimbursement for this? I'm not too fussed about the second receipt or rotating the image.

**Comment by lwjohnst86** [comment]
You haven't been reimbursed for this yet?

**Comment by lwjohnst86** [comment]
There's an issue with treasurer/receipts/2018-02-20-StarbucksGiftCards-Starbucks2.JPG and the one currently in this PR (treasurer/receipts/2017-12-07-StarbucksCards.jpg)... they are both the same. You have the actual 2018 one still?

**Comment by lwjohnst86** [comment]
Otherwise this PR is fine to merge... But the previous receipt needs to be fixed.

**Comment by nsahin** [comment]
I don't think I can see this file (treasurer/receipts/2017-12-07-StarbucksCards.jpg). Is there still a problem or should I merge?

**Comment by lwjohnst86** [comment]
Ah, I see what happened. @nsahin the receipts should probably be dated for the time that is on the receipt, not when the reimbursement was requested. But not a huge deal. @mbonsma yes, this can be closed then.

**Pull request closed without merging**
