### PR TITLE
Social drinks

### PR DESCRIPTION
**Pull request by mbonsma**

### CODE REVIEW

**Comment by QuLogic** [comment]
You forgot to sign these commits. Also, the receipt is pretty large; not sure if you want to shrink it a bit. It would require remaking the commit entirely though.

**Comment by lwjohnst86** [comment]
Yea, almost 8Mb for a receipt is big. Probably don't want that in the history. Can it be completely redone even tho it's been pushed up?

**Comment by QuLogic** [comment]
Sure, PRs track the branch.

**Comment by QuLogic** [comment]
Sorry, but if you want to reduce the size, you need to rebase and amend the original commit. The large file is still there in the original commit. I can show you next week.

**Comment by lwjohnst86** [comment]
Damn, forgot to do this today. I understand you're busy @mbonsma, so I can deal with fixing this and push my own branch up. I'll just get you to +1 it or comment on it or something.

**Comment by lwjohnst86** [comment]
Made a new PR (#37) with smaller file size. Closing this one. @mbonsma you can delete your local social branch. @QuLogic will that remove the file from her commit history? Or would it matter really since it's on her forked version?

**Comment by QuLogic** [comment]
If you delete the branch here and on your computer, the old file will stick around for a little bit (as will the commits), but eventually they'll expire and be garbage collected.

**Pull request closed without merging**
