### PR TITLE
Added reimbursing info for Luke

### PR DESCRIPTION
**Pull request by lwjohnst86**

### CODE REVIEW

**Comment by QuLogic** [comment]
How does this relate to #59?

**Comment by mbonsma** [comment]
@QuLogic I submitted these receipts to Mozilla as part of the fund they gave us for the Hack Day. So the first two receipts and the last receipt in #59 are these ones.

**Comment by QuLogic** [comment]
Yes, I mean transfer-wise...

**Comment by lwjohnst86** [comment]
Right, was planning on closing this (not merging) after I received the money, because I wasn't sure how we would end up doing it. Keep me updated on the Mozilla process!

**Comment by lwjohnst86** [comment]
@mbonsma any update on the money refund from MSL?

**Comment by mbonsma** [comment]
@lwjohnst86 no, not yet. I haven't seen the money in my account and I haven't heard anything about my expense report. In another week or so I'll email them to follow up.

**Comment by lwjohnst86** [comment]
@mbonsma another bump. No word yet from MSL? This is taking waaay too long..

**Comment by lwjohnst86** [comment]
@mbonsma will give a cheque from MSL for this and #111 and #112

**Pull request merged**
