### PR TITLE
Reimburse Dawn Walker (@dcwalk)

### PR DESCRIPTION
**Pull request by lwjohnst86**
I'm submitting this for @dcwalk. @mbonsma could you approve this PR? Also, you around to sign cheque this Monday?

### CODE REVIEW

**Comment by mbonsma** [comment]
Looks good to me!

**Comment by lwjohnst86** [comment]
@dcwalk I'm going to need you to also approve this, for record keeping. Thanks!

**Comment by lwjohnst86** [comment]
@dcwalk, scratch that, just saw your +1 to the original PR comment. nvm!! :D

**Comment by dcwalk** [comment]
Okay great! But for posterity: I approve the request, these reflect my expenses!

**Pull request merged**
