### PR TITLE
Snacks for SWC May 26-27

### PR DESCRIPTION
**Pull request by mbonsma**

### CODE REVIEW

**Comment by lwjohnst86** [comment]
drat.. we haven't done the key signing party yet.. :( I'd like the reimbursement forms to be GPG signed. Maybe we can do this tomorrow? @QuLogic @mbonsma will both of you be there?

**Comment by lwjohnst86** [comment]
Looks great though! I'll bring the cheque. Can you bring the hardcopy receipt?

**Comment by mbonsma** [comment]
Yup I'll be there! I looked at the GPG stuff and got confused, so yeah let's do it tomorrow. I'll bring the hard copy receipt.

**Comment by QuLogic** [comment]
I'm a bit busy today, so I don't think I'll be there today.

**Comment by lwjohnst86** [comment]
@QuLogic whenever you're not busy, can you approve (+1) this PR since Maddy will be the one signing (given the cheque will be for Maddy).

**Comment by lwjohnst86** [comment]
Yeaaayyyy! Verified with GPG :)

**Pull request merged**
